version: "3"
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "./selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid:/opt/selenoid/logs"
    command: ["-conf", "/etc/selenoid/browsers.json", "-log-output-dir", "/opt/selenoid"]
    ports:
      - "4444:4444"
