use_field_init_shorthand = true
use_small_heuristics = "Max"
merge_derives = true
newline_style = "Unix"

# unstable
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
format_strings = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
merge_imports = true
reorder_impl_items = true

