name: build

on:
  push:
    branches:
      - masteer
  pull_request:

jobs:
  api:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/.git
            api/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        working-directory: ./api
        run: cargo build
