name: build

on:
  push:
    branches:
      - masteer
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: setting up cargo
        working-directory: ./api
        run: cargo build
