name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: setting up cargo
        uses: actions-rs/cargo@v1
        working-directory: ./api
        with:
          command: build
